# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0003_codingquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestion',
            name='sample_output',
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='solution',
            field=models.CharField(max_length=10000000, null=True),
        ),
    ]
