# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0006_auto_20171021_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestion',
            name='output',
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='sample_output',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
