# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0008_codingquestion_difficulty_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coder_facebook_id', models.CharField(max_length=100, unique=True)),
                ('question_solved', models.CharField(max_length=1000000, unique=True)),
                ('last_testcase_passed', models.IntegerField()),
            ],
        ),
    ]
