# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0009_codingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingresult',
            name='last_testcase_passed',
        ),
        migrations.RemoveField(
            model_name='codingresult',
            name='question_solved',
        ),
        migrations.AddField(
            model_name='codingresult',
            name='last_testcase_passed_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='codingresult',
            name='question_solved_id',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='codingresult',
            name='coder_facebook_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
