# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0010_auto_20171026_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingresult',
            name='question_solved_id',
            field=models.IntegerField(null=True),
        ),
    ]
