# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0011_auto_20171026_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingresult',
            name='last_testcase_passed_index',
            field=models.IntegerField(default=0),
        ),
    ]
