# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0012_auto_20171026_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresult',
            name='coder_source_code',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
