# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0013_codingresult_coder_source_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger_id', models.CharField(max_length=100, unique=True)),
                ('profile_details', models.CharField(max_length=1000000, null=True)),
                ('facebook_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hway.FacebookUser')),
            ],
        ),
    ]
