# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0014_botuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='difficulty_level',
            field=models.CharField(choices=[('simple', 'Simple'), ('intermediate', 'Intermediate'), ('difficult', 'Difficult')], max_length=10, null=True),
        ),
    ]
