# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0016_auto_20171101_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('30', 'Python 3')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('difficulty_level', models.CharField(choices=[('simple', 'Simple'), ('intermediate', 'Intermediate'), ('difficult', 'Difficult')], max_length=20)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hway.ProgrammingLanguage')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('1', 'Right'), ('2', 'Wrong')], max_length=10)),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hway.ProgrammingQuestion')),
            ],
        ),
    ]
