# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0017_programminglanguage_programmingquestion_programmingquestionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(choices=[('30', 'Python 3')], max_length=30, unique=True),
        ),
    ]
