# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0018_auto_20171103_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
