# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0019_auto_20171103_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='current_questions_ids',
            field=models.CharField(default='[]', max_length=1000000),
        ),
        migrations.AddField(
            model_name='botuser',
            name='json_store',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='questions_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botuser',
            name='questions_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hway.ProgrammingLanguage'),
        ),
        migrations.AlterField(
            model_name='programmingquestionanswer',
            name='related_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hway.ProgrammingQuestion'),
        ),
    ]
