# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0020_auto_20171103_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='json_store',
            field=models.CharField(default='{}', max_length=1000000),
        ),
    ]
