# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0021_auto_20171103_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='current_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botuser',
            name='possible_total',
            field=models.IntegerField(default=0),
        ),
    ]
