# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0022_auto_20171103_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresult',
            name='error',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='codingresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
