# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0023_auto_20171104_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingresult',
            old_name='score',
            new_name='current_score',
        ),
        migrations.AddField(
            model_name='codingresult',
            name='previous_score',
            field=models.IntegerField(default=0),
        ),
    ]
