# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0025_auto_20171104_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='scores',
            field=models.CharField(default='[]', max_length=1000000),
        ),
    ]
