# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0026_botuser_scores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='current_total',
            new_name='quiz_total',
        ),
    ]
