# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0027_auto_20171104_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
