# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0028_auto_20171104_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookuser',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
