# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0029_facebookuser_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='profile_picture_url',
            field=models.URLField(null=True),
        ),
    ]
