# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0030_auto_20171106_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookuser',
            name='private_api_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='public_api_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
