# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0031_auto_20171107_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
