# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0032_auto_20171107_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='solution_language',
            field=models.CharField(choices=[('30', 'Python3'), ('5', 'Python2')], max_length=3, null=True),
        ),
    ]
