# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0034_codingquestion_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programming_questions_images'),
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
