# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0036_auto_20171109_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hway.ProgrammingCategory'),
        ),
    ]
