# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0040_auto_20171111_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='question_challenged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botuser',
            name='question_data',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
