# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0041_auto_20171111_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='generated_quiz_data',
            field=models.BooleanField(default=False),
        ),
    ]
