# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0043_auto_20171112_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='generating_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
