# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0044_botuser_generating_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='generated_quiz_data',
            field=models.CharField(default='{}', max_length=100000, null=True),
        ),
    ]
