# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0045_botuser_generated_quiz_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='generated_quiz_data',
            new_name='generated_quiz_results',
        ),
    ]
