# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 14:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0046_auto_20171115_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('students', models.ManyToManyField(to='hway.FacebookUser')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='solution_language',
            field=models.TextField(choices=[('30', 'Python3'), ('5', 'Python2')], null=True),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='course_segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hway.CourseSegment'),
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='course_segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hway.CourseSegment'),
        ),
    ]
