# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 15:12
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0047_auto_20171121_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesegment',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
