# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0048_auto_20171121_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='solution',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='solution_language',
            field=models.CharField(choices=[('30', 'Python3'), ('5', 'Python2')], max_length=4, null=True),
        ),
    ]
