# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0049_auto_20171121_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesegment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hway.Course'),
        ),
    ]
