# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0053_auto_20171122_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_segment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coursesegment',
            name='question_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesegment',
            name='quiz_solved',
            field=models.BooleanField(default=False),
        ),
    ]
