# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0055_auto_20171123_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='solving_course_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
