# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0057_auto_20171123_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='current_segment_id',
        ),
        migrations.RemoveField(
            model_name='coursesegment',
            name='question_solved',
        ),
        migrations.RemoveField(
            model_name='coursesegment',
            name='quiz_solved',
        ),
        migrations.AddField(
            model_name='botuser',
            name='course_data',
            field=models.CharField(default='{"data": []}', max_length=1000000),
        ),
        migrations.AddField(
            model_name='coursesegment',
            name='intro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='coursesegment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_segments', to='hway.Course'),
        ),
    ]
