# Generated by Django 2.0.6 on 2018-06-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0060_facebookuser_private_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='coursesegment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='codingquestion',
            name='course_segment',
        ),
        migrations.RemoveField(
            model_name='programmingquestion',
            name='course_segment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseSegment',
        ),
    ]
