# Generated by Django 2.0.6 on 2018-06-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0062_remove_facebookuser_private_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='course_data',
        ),
    ]
